# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint, test and build

on:
  push:
    branches: [ master ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.9.7"
    - name: Install dependencies
      run: |
        sudo apt-get install libgtk-3-dev
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
  compile:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.7"
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install libgtk-3-dev
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Compile with pyinstaller
        run: pyinstaller -F --name="PDF Converter" __main__.py
      - uses: actions/upload-artifact@v2
        with:
          name: PDF Converter
          path: ./dist/

    

